### ISSUE TITLE
关于18.04melodic系统的适配程度

### ISSUE THREAD

**Issue by fairytailing** [XKHoshizora/qt6_ros_template#1]
博主您好，请问18.04 melodic系统能按照这个教程安装Qt6吗

**Comment by XKHoshizora** [comment]
> 博主您好，请问18.04 melodic系统能按照这个教程安装Qt6吗

感谢提问！

虽然 Ubuntu 18.04 默认支持 Qt5 没有 Qt6，但应该是可以在 Ubuntu 18.04 上安装和使用 Qt6，只是过程中可能会需要一些额外的步骤。

可以先尝试使用官网的在线安装程序，对照着本项目的说明进行安装和环境配置，或尝试使用以下命令安装 Qt6：

```bash
sudo add-apt-repository ppa:beineri/opt-qt-6.2.4-bionic
sudo apt-get update
sudo apt-get install qt62base qt62tools
```

配置 Qt6 环境：

```bash
source /opt/qt62/bin/qt62-env.sh
```

由于我自己搭建和测试的环境是 Ubuntu 20.04 以上的版本，因此还未尝试过 Ubuntu 18.04 环境下的安装，如果过程中出现什么问题，欢迎继续提问，到时候请说明操作的步骤和报出的错误。

另外，由于 Qt6 是在 2020 年 12 月发布的，而 ROS Melodic（发布于 2018 年）和 Ubuntu 18.04 默认使用的是 Qt5，如果不执着于使用 Qt6 的话，可以尝试 Qt5，应该会更加简单一些。

**Comment by fairytailing** [comment]
感谢博主的回复！明天我会尝试一下按照您的教程安装Qt6或者Qt5。
